pulp_default_admin_password: password
pulp_install_plugins:
  # pulp-ansible: {}
  # pulp-certguard: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-docker: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-python: {}
  # pulp-rpm:
  #   prereq_role: "/home/vagrant/devel/pulp-rpm-prerequisites"
  pulp-file: {}

# Uncomment if using pulp-rpm
#pulp_use_system_wide_pkgs: true
pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
