pulp_default_admin_password: password
pulp_install_plugins:
  # pulp-ansible: {}
  # galaxy-pulp: {}
  # galaxy-ng: {}
  # pulp-certguard: {}
  # pulp-cookbook: {}
  # pulp-deb: {}
  # pulp-container: {}
  # pulp-gem: {}
  # pulp-maven: {}
  # pulp-python: {}
  # pulp-rpm:
  #   prereq_role: "pulp.pulp_rpm_prerequisites"
  pulp-file: {}

pulp_settings:
  secret_key: "unsafe_default"
  content_origin: "http://{{ ansible_fqdn }}"
